using Test

include("test_helpers.jl")
include("test_model.jl")
include("test_mobile_labor.jl")
include("test_fixed_closure.jl")
include("test_kernel_regression.jl")
include("test_promoted_closures.jl")
include("test_calibration.jl")
include("test_gdp_measurement.jl")
include("test_external_closure.jl")
include("test_sectoral_labour.jl")
include("test_run_manifest.jl")
include("test_f1_tilt.jl")
include("test_check_repo.jl")
include("test_variance_decomposition.jl")
include("test_eta_sweep.jl")
